//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.635, BuildCommit: 356a242b2988b83197d263f19396861841292988)
//
//   Extracted from: CoreBrightness.framework
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 18.7, SDK: 18.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 1902.140.5.0.0
//

@class BrightnessSystemClient;

@protocol OS_os_log;

@interface KeyboardBrightnessClient : NSObject {
    /* instance variables */
    BrightnessSystemClient *bsc;
    NSObject<OS_os_log> *_logHandle;
}

/* instance methods */
- (void)dealloc;
- (id _Nonnull)init;
- (_Bool)isBacklightSaturatedOnKeyboard:(unsigned long long)keyboard;
- (_Bool)suspendIdleDimming:(_Bool)dimming forKeyboard:(unsigned long long)keyboard;
- (float)backlightLevelForKeyboard:(unsigned long long)keyboard;
- (float)brightnessForKeyboard:(unsigned long long)keyboard;
- (id)copyKeyboardBacklightIDs;
- (_Bool)enableAutoBrightness:(_Bool)brightness forKeyboard:(unsigned long long)keyboard;
- (double)idleDimTimeForKeyboard:(unsigned long long)keyboard;
- (_Bool)isAmbientFeatureAvailableOnKeyboard:(unsigned long long)keyboard;
- (_Bool)isAutoBrightnessEnabledForKeyboard:(unsigned long long)keyboard;
- (_Bool)isBacklightDimmedOnKeyboard:(unsigned long long)keyboard;
- (_Bool)isBacklightSuppressedOnKeyboard:(unsigned long long)keyboard;
- (_Bool)isIdleDimmingSuspendedOnKeyboard:(unsigned long long)keyboard;
- (_Bool)isKeyboardBuiltIn:(unsigned long long)in;
- (void)registerNotificationForKeys:(id)keys keyboardID:(unsigned long long)id block:(id /* block */)block;
- (_Bool)setBrightness:(float)brightness fadeSpeed:(int)speed commit:(_Bool)commit forKeyboard:(unsigned long long)keyboard;
- (_Bool)setBrightness:(float)brightness forKeyboard:(unsigned long long)keyboard;
- (_Bool)setIdleDimTime:(double)time forKeyboard:(unsigned long long)keyboard;
- (void)unregisterKeyboardNotificationBlock;

@end
