//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.635, BuildCommit: 356a242b2988b83197d263f19396861841292988)
//
//   Extracted from: OSD.framework
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 15.7, SDK: 15.7, Tool: ld (1167.3)
//    - LC_SOURCE_VERSION: 43.0.0.0.0
//

// MARK: - OSDUIHelperProtocol.h

@class NSString;

@protocol OSDUIHelperProtocol
- (void)showFullScreenImage:(long long)arg1 onDisplayID:(unsigned int)arg2 priority:(unsigned int)arg3 msecToAnimate:(unsigned int)arg4;
- (void)fadeClassicImageOnDisplay:(unsigned int)arg1;
- (void)showImageAtPath:(NSString *)arg1 onDisplayID:(unsigned int)arg2 priority:(unsigned int)arg3 msecUntilFade:(unsigned int)arg4 withText:(NSString *)arg5;
- (void)showImage:(long long)arg1 onDisplayID:(unsigned int)arg2 priority:(unsigned int)arg3 msecUntilFade:(unsigned int)arg4 filledChiclets:(unsigned int)arg5 totalChiclets:(unsigned int)arg6 locked:(BOOL)arg7;
- (void)showImage:(long long)arg1 onDisplayID:(unsigned int)arg2 priority:(unsigned int)arg3 msecUntilFade:(unsigned int)arg4 withText:(NSString *)arg5;
- (void)showImage:(long long)arg1 onDisplayID:(unsigned int)arg2 priority:(unsigned int)arg3 msecUntilFade:(unsigned int)arg4;
@end


// MARK: - OSDManager.h

@interface OSDManager : NSObject <OSDUIHelperProtocol> {
    /* instance variables */
    id <OSDUIHelperProtocol> _proxyObject;
}

@property (retain) NSXPCConnection *connection;
@property (readonly) id <OSDUIHelperProtocol> remoteObjectProxy;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (void)fadeClassicImageOnDisplay:(unsigned int)display;
- (void)showFullScreenImage:(long long)image onDisplayID:(unsigned int)id priority:(unsigned int)priority msecToAnimate:(unsigned int)animate;
- (void)showImage:(long long)image onDisplayID:(unsigned int)id priority:(unsigned int)priority msecUntilFade:(unsigned int)fade;
- (void)showImage:(long long)image onDisplayID:(unsigned int)id priority:(unsigned int)priority msecUntilFade:(unsigned int)fade filledChiclets:(unsigned int)chiclets totalChiclets:(unsigned int)chiclets locked:(_Bool)locked;
- (void)showImage:(long long)image onDisplayID:(unsigned int)id priority:(unsigned int)priority msecUntilFade:(unsigned int)fade withText:(id)text;
- (void)showImageAtPath:(id)path onDisplayID:(unsigned int)id priority:(unsigned int)priority msecUntilFade:(unsigned int)fade withText:(id)text;

@end
